HunterGuide.Quest = DS.Model.extend({
  title:      DS.attr('string'),
  rank:       DS.belongsTo('rank', { async: true }),
  type:       DS.attr('string'),
  objective:  DS.attr('string'),
  subquest:   DS.attr('string'),
  location:   DS.attr('string'),
  monsters :  DS.attr('string'),
  isKeyQuest: DS.attr('boolean')
});

HunterGuide.Quest.FIXTURES = [
   {
      id: 1,
      title: "Harvest Tour: Ancestral Steppe",
      rank: 1,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Aptonoth, Altaroth, Jaggi, Seltas, Great Jaggi, Kecha Wacha"
   },
   {
      id: 2,
      title: "Harvest Tour: Sunken Hollow",
      rank: 1,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Altaroth, Konchu, Genprey, Gendrome, Kecha Wacha"
   },
   {
      id: 3,
      title: "Local Yolk",
      rank: 1,
      type: "Egg",
      objective: "Deliver 4 Gargwa Eggs",
      subquest: "Deliver 1 Gold Gargwa Egg",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Gargwa, Jaggi, Melynx, Great Jaggi"
   },
   {
      id: 4,
      title: "Fishing's Lure",
      rank: 1,
      type: "Delivery",
      objective: "Deliver 8 Small Goldenfish",
      subquest: "Deliver 4 Sushifish",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Konchu, Genprey, Tetsucabra"
   },
   {
      id: 5,
      title: "Ancestral Steppe Fungus Run",
      rank: 1,
      type: "Delivery",
      objective: "Deliver 8 Unique Mushrooms",
      subquest: "Deliver 3 Choice Mushrooms",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Konchu, Jaggi, Kecha Wacha"
   },
   {
      id: 6,
      title: "Konchu Collector",
      rank: 1,
      type: "Hunting",
      objective: "Slay 10 Konchu",
      subquest: "N/A",
      location: "Ancestral Steppe",
      monsters: "Konchu, Jaggi, Seltas"
   },
   {
      id: 7,
      title: "Bnahabra Bloodbath",
      rank: 1,
      type: "Hunting",
      objective: "Slay 12 Bnahabra",
      subquest: "Slay 6 Altaroth",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Bnahabra, Altaroth, Seltas"
   },
   {
      id: 8,
      title: "Genprey Payback",
      rank: 1,
      type: "Hunting",
      objective: "Slay 10 Genprey",
      subquest: "N/A",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Genprey"
   },
   {
      id: 9,
      title: "Rhenoplos Headache",
      rank: 1,
      type: "Hunting",
      objective: "Slay 8 Rhenoplos",
      subquest: "N/A",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Tetsucabra"
   },
   {
      id: 10,
      title: "Bug Burger",
      rank: 1,
      type: "Hunting",
      objective: "Hunt a Seltas",
      subquest: "Break the Seltas's horn",
      location: "Ancestral Steppe",
      isKeyQuest: true,
      monsters: "Konchu, Jaggi"
   },
   {
      id: 11,
      title: "Field Trip",
      rank: 1,
      type: "Hunting",
      objective: "Hunt a Great Jaggi",
      subquest: "Wound the Great Jaggi's head",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Jaggi, Jaggia"
   },
   {
      id: 12,
      title: "Kecha Konundrum",
      rank: 1,
      type: "Hunting",
      objective: "Hunt a Kecha Wacha",
      subquest: "Wound the Kecha Wacha's ears",
      location: "Ancestral Steppe",
      isKeyQuest: true,
      monsters: "Jaggi, Jaggia"
   },
   {
      id: 13,
      title: "Tackling a Tetsucabra",
      rank: 1,
      type: "Hunting",
      objective: "Hunt a Tetsucabra",
      subquest: "Wound the Tetsucabra's jaw",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Genprey, Konchu"
   },
   {
      id: 14,
      title: "The Gypceros Project",
      rank: 1,
      type: "Capture",
      objective: "Capture a Gypceros",
      subquest: "Slay 5 Konchu",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Genprey, Konchu"
   },
   {
      id: 15,
      title: "Operation Catch-a-Kecha",
      rank: 1,
      type: "Capture",
      objective: "Capture a Kecha Wacha",
      subquest: "Break the Kecha Wacha's claw",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Genprey, Konchu"
   },
   {
      id: 16,
      title: "Robbed Blind",
      rank: 1,
      type: "Hunting",
      objective: "Hunt a Gypceros",
      subquest: "Wound the Gypceros' crest",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Jaggi, Jaggia"
   },
   {
      id: 17,
      title: "Web Sighting",
      rank: 1,
      type: "Urgent",
      objective: "Hunt a Nerscylla",
      subquest: "Break Nerscylla's poison spikes",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Genprey, Konchu"
   },
   {
      id: 18,
      title: "Harvest Tour: Primal Forest",
      rank: 2,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Altaroth, Conga, Gypceros, Gendrome"
   },
   {
      id: 19,
      title: "Harvest Tour: Frozen Seaway",
      rank: 2,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Popo, Zamite, Zamtrios, Lagombi"
   },
   {
      id: 20,
      title: "Web Sighting",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Nerscylla",
      subquest: "Break Nerscylla's poison spikes",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Genprey, Konchu"
   },
   {
      id: 21,
      title: "Sootstone Search",
      rank: 2,
      type: "Delivery",
      objective: "Deliver 3 Sootstones",
      subquest: "Deliver 4 Sulphur Crystals",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Melynx, Kecha Wacha"
   },
   {
      id: 22,
      title: "Bite Your Tongues",
      rank: 2,
      type: "Delivery",
      objective: "Deliver 6 Popo tongues",
      subquest: "N/A",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Popo, Zamite, Zamtrios, Lagombi"
   },
   {
      id: 23,
      title: "Stone-cold Stones",
      rank: 2,
      type: "Delivery",
      objective: "Deliver 8 Bloodstones",
      subquest: "N/A",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Popo, Zamite, Khezu"
   },
   {
      id: 24,
      title: "Zamite Fight",
      rank: 2,
      type: "Hunting",
      objective: "Slay 10 Zamite",
      subquest: "N/A",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Zamite, Popo, Zamtrios"
   },
   {
      id: 25,
      title: "Conga Bongo",
      rank: 2,
      type: "Hunting",
      objective: "Slay 8 Conga",
      subquest: "N/A",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Conga, Slagtoth, Congalala"
   },
   {
      id: 26,
      title: "Gendrome Roadblock",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Gendrome",
      subquest: "Slay 6 Genprey",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Genprey, Bnahabra"
   },
   {
      id: 27,
      title: "Royal Assassination",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Rathian",
      subquest: "Wound the Rathian's head",
      location: "Ancestral Steppe",
      isKeyQuest: true,
      monsters: "Aptonoth, Jaggi"
   },
   {
      id: 28,
      title: "Snow with Occasional Lagombi",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Lagombi",
      subquest: "Wound the Lagombi's head",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Popo, Zamite"
   },
   {
      id: 29,
      title: "A Ghastly Gift",
      rank: 2,
      type: "Capture",
      objective: "Capture a Khezu",
      subquest: "Wound the Khezu's body",
      location: "Frozen Seaway",
      isKeyQuest: true,
      monsters: "Popo, Zamite"
   },
   {
      id: 30,
      title: "Zamtrios of the Deep",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Zamtrios",
      subquest: "Break the Zamtrios's head",
      location: "Frozen Seaway",
      isKeyQuest: true,
      monsters: "Bnahabra, Zamite"
   },
   {
      id: 31,
      title: "Eau de Congalala",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Congalala",
      subquest: "Wound the Congalala's comb",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Bnahabra, Conga, Genprey, Kelbi, Konchu, Slagtoth"
   },
   {
      id: 32,
      title: "Nix the Najarala",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Najarala",
      subquest: "Wound the Najarala's back",
      location: "Primal Forest",
      isKeyQuest: true,
      monsters: "Genprey, Conga"
   },
   {
      id: 33,
      title: "Subterranean Serenade",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Nerscylla and a Gypceros",
      subquest: "Wound the Nerscylla's hide",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey"
   },
   {
      id: 34,
      title: "Tails from the Sunken Hollow",
      rank: 2,
      type: "Hunting",
      objective: "Hunt 2 Khezu",
      subquest: "Deliver 1 Wyvern Tear",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey"
   },
   {
      id: 35,
      title: "Snowed In",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Zamtrios and a Lagombi",
      subquest: "Deliver 1 Toad Tear",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Bnahabra, Zamite"
   },
   {
      id: 36,
      title: "Field Study: Primal Forest",
      rank: 2,
      type: "Hunting",
      objective: "Hunt a Najarala and a Rathian",
      subquest: "Wound the Najarala's tail",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Genprey, Conga"
   },
   {
      id: 37,
      title: "Dark Wings, Dark Work",
      rank: 2,
      type: "Urgent",
      objective: "Hunt a Gore Magala",
      subquest: "Wound Gore Magala's wing",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Gargwa, Jaggi"
   },
   {
      id: 38,
      title: "Harvest Tour: Heaven's Mount",
      rank: 3,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Heaven's Mount",
      isKeyQuest: false,
      monsters: "Ioprey, Remobra, Zinogre, Rathalos, Seltas"
   },
   {
      id: 39,
      title: "Harvest Tour: Volcanic Hollow",
      rank: 3,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Volcanic Hollow",
      isKeyQuest: false,
      monsters: "Ioprey, Slagtoth, Iodrome, Gravios"
   },
   {
      id: 40,
      title: "Dark Wings, Dark Work",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Gore Magala",
      subquest: "Wound Gore Magala's wing",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Gargwa, Jaggi"
   },
   {
      id: 41,
      title: "Tigrex Tough Love",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Tigrex",
      subquest: "Break the Tigrex's claw",
      location: "Ancestral Steppe",
      isKeyQuest: true,
      monsters: "Gargwa, Aptonoth, Jaggi"
   },
   {
      id: 42,
      title: "Heat Exhaustion",
      rank: 3,
      type: "Egg",
      objective: "Deliver 3 Powderstone",
      subquest: "Hunt an Iodrome",
      location: "Volcanic Hollow",
      isKeyQuest: false,
      monsters: "Iodrome, Gravios"
   },
   {
      id: 43,
      title: "Energy Crisis",
      rank: 3,
      type: "Delivery",
      objective: "Deliver 10 Coal",
      subquest: "Sever a Gravios's tail",
      location: "Volcanic Hollow",
      isKeyQuest: false,
      monsters: "Gravios"
   },
   {
      id: 44,
      title: "Ioprey In the Way",
      rank: 3,
      type: "Hunting",
      objective: "Slay 12 Ioprey",
      subquest: "N/A",
      location: "Volcanic Hollow",
      isKeyQuest: false,
      monsters: "Ioprey, Rhenoplos, Iodrome"
   },
   {
      id: 45,
      title: "Remobra Remedy",
      rank: 3,
      type: "Hunting",
      objective: "Slay 7 Remobra",
      subquest: "N/A",
      location: "Heaven's Mount",
      isKeyQuest: false,
      monsters: "Remobra, Bnahabra, Rathian"
   },
   {
      id: 46,
      title: "Temper Tantrum",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Gravios",
      subquest: "Wound the Gravios's back",
      location: "Volcanic Hollow",
      isKeyQuest: true,
      monsters: "Ioprey, Bnahabra"
   },
   {
      id: 47,
      title: "Pick Your Poison",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Iodrome",
      subquest: "Deliver 1 Wyvern Tear",
      location: "Volcanic Hollow",
      isKeyQuest: false,
      monsters: "Ioprey, Bnahabra"
   },
   {
      id: 48,
      title: "Royal Audience",
      rank: 3,
      type: "Capture",
      objective: "Capture a Rathalos",
      subquest: "Wound the Rathalos's wings",
      location: "Heaven's Mount",
      isKeyQuest: true,
      monsters: "Ioprey, Aptonoth"
   },
   {
      id: 49,
      title: "Rathalos Run",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Rathalos",
      subquest: "Wound the Rathalos's head",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Aptonoth, Jaggi"
   },
   {
      id: 50,
      title: "Tuff Turf",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Zinogre",
      subquest: "Wound the Zinogre's head",
      location: "Heaven's Mount",
      isKeyQuest: true,
      monsters: "Ioprey, Kelbi"
   },
   {
      id: 51,
      title: "The Royal Guard",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Seltas Queen",
      subquest: "Wound the Seltas Queen's tail",
      location: "Heaven's Mount",
      isKeyQuest: true,
      monsters: "Ioprey, Kelbi"
   },
   {
      id: 52,
      title: "The Angry Couple",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Rathian and a Rathalos",
      subquest: "Sever the Rathalos's tail",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Aptonoth, Jaggi"
   },
   {
      id: 53,
      title: "Queen and Rook",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Rathian and a Gravios",
      subquest: "Deliver 1 Wyvern Tear",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Slagtoth, Konchu"
   },
   {
      id: 54,
      title: "Hunter's Heaven",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Tigrex and a Zinogre",
      subquest: "Deliver 1 Wyvern Tear",
      location: "Heaven's Mount",
      monsters: "Ioprey, Aptonoth"
   },
   {
      id: 55,
      title: "Advanced: Rock and Rolled",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Brachydios",
      subquest: "Wound Brachydios's front leg",
      location: "Volcanic Hollow",
      isKeyQuest: false,
      monsters: "Ioprey, Rhenoplos"
   },
   {
      id: 56,
      title: "Advanced: Family Business",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Frenzied Gravios",
      subquest: "Wound the Gravios's chest",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Slagtoth, Genprey"
   },
   {
      id: 57,
      title: "Advanced: Fearsome Rumblings",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Frenzied Tigrex",
      subquest: "Wound the Tigrex's head",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Popo, Zamite"
   },
   {
      id: 58,
      title: "Advanced: Approaching Storm",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Frenzied Zinogre",
      subquest: "Wound the Zinogre's back",
      location: "Heaven's Mount",
      isKeyQuest: false,
      monsters: "Ioprey, Remobra"
   },
   {
      id: 59,
      title: "Advanced: Bug Buffet",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Frenzied Seltas Queen",
      subquest: "Hunt a Seltas",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Genprey, Slagtoth, Seltas"
   },
   {
      id: 60,
      title: "Advanced: Purge and Binge",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Frenzied Tetsucabra and a Frenzied Zamtrios",
      subquest: "Wound the Zamtrios's tail",
      location: "Frozen Seaway",
      isKeyQuest: false,
      monsters: "Popo, Zamite"
   },
   {
      id: 61,
      title: "Advanced: One-man Army",
      rank: 3,
      type: "Hunting",
      objective: "Hunt a Frenzied Nerscylla and a Frenzied Kecha Wacha",
      subquest: "Wound the Kecha Wacha's tail",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey"
   },
   {
      id: 62,
      title: "Advanced: Sand Sailor",
      rank: 3,
      type: "Urgent",
      objective: "Slay Dah'ren Mohran or repel it",
      subquest: "Break Dah'ren Mohran's horn",
      location: "Great Desert",
      isKeyQuest: true,
      monsters: "Delex"
   },
   {
      id: 63,
      title: "Harvest Tour: Anc. Steppe",
      rank: 4,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Altaroth, Jaggi, Deviljho, Great Jaggi"
   },
   {
      id: 64,
      title: "Harvest Tour: Sunken Hollow",
      rank: 4,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Altaroth, Deviljho, Gendrome, Savage Deviljho"
   },
   {
      id: 65,
      title: "Harvest Tour: Primal Forest",
      rank: 4,
      type: "Gathering",
      objective: "Survive until time expires or deliver a Paw Pass Ticket",
      subquest: "N/A",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Slagtoth, Genprey, Deviljho, Gypceros, Savage Deviljho"
   },
   {
      id: 66,
      title: "Rhenoplos Headache",
      rank: 4,
      type: "Hunting",
      objective: "Slay 10 Rhenoplos",
      subquest: "N/A",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey, Gendrome"
   },
   {
      id: 67,
      title: "Bnahabra Bloodbath",
      rank: 4,
      type: "Hunting",
      objective: "Slay 20 Bnahabra",
      subquest: "Slay 8 Altaroth",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Bnahabra, Altaroth, Gypceros"
   },
   {
      id: 68,
      title: "Pack Attack",
      rank: 4,
      type: "Hunting",
      objective: "Hunt 2 Great Jaggi",
      subquest: "Slay 6 Jaggia",
      location: "Ancestral Steppe",
      isKeyQuest: false,
      monsters: "Jaggi, Jaggia"
   },
   {
      id: 69,
      title: "Seltas Romance",
      rank: 4,
      type: "Hunting",
      objective: "Hunt 2 Seltas",
      subquest: "Slay 10 Konchu",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Konchu, Bnahabra"
   },
   {
      id: 70,
      title: "Face Two Face",
      rank: 4,
      type: "Hunting",
      objective: "Hunt 2 Kecha Wacha",
      subquest: "Deliver 1 Large Beast Tear",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Jaggi, Aptonoth"
   },
   {
      id: 71,
      title: "Operation Catch-a-Kecha",
      rank: 4,
      type: "Capture",
      objective: "Capture a [Kecha Wacha]",
      subquest: "Wound the Kecha Wacha's ears",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey, Purple Gypceros, Deviljho, Savage Deviljho"
   },
   {
      id: 72,
      title: "Purple People Eater",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Purple Gypceros",
      subquest: "Would Purple Gypceros's crest",
      location: "Primal Forest",
      isKeyQuest: true,
      monsters: "Slagtoth, Genprey, Gypceros, Deviljho, Savage Deviljho"
   },
   {
      id: 73,
      title: "Gypceros Overload",
      rank: 4,
      type: "Hunting",
      objective: "Hunt 2 or more Gypceros and deliver 1 Paw Pass Ticket",
      subquest: "Deliver 1 Large Wyvern Tear",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Aptonoth, Genprey"
   },
   {
      id: 74,
      title: "Tetsucabra Bounty",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Tetsucabra",
      subquest: "Wound the Tetsucabra's hing leg",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Jaggi, Jaggia, Gendrome, Deviljho, Savage Deviljho"
   },
   {
      id: 75,
      title: "Buffoonish Baboon",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Emerald Congalala",
      subquest: "Wound Emerald Congalala's comb",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Aptonoth, Genprey, Gendrome, Deviljho, Savage Deviljho"
   },
   {
      id: 76,
      title: "Arachnophilia",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Nerscylla",
      subquest: "Wound the Nerscylla's claw",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Slagtoth, Genprey, Gypceros, Deviljho, Savage Deviljho"
   },
   {
      id: 77,
      title: "Dastardly Duo",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Gendrome and a Tetsucabra",
      subquest: "Wound the Gendrome's head",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Genprey, Bnahabra"
   },
   {
      id: 78,
      title: "Gold in Them There Fish",
      rank: 4,
      type: "Fishing",
      objective: "Deliver 10 Goldenfish",
      subquest: "Deliver 5 Sushifish",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Slagtoth, Bnahabra, Emerald Congalala, Purple Gypceros"
   },
   {
      id: 79,
      title: "Splendid Sootstone",
      rank: 4,
      type: "Egg",
      objective: "Deliver 4 Sootstone",
      subquest: "Sever the Deviljho's tail",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey, Deviljho"
   },
   {
      id: 80,
      title: "Apes of Wrath",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Kecha Wacha and a Emerald Congalala",
      subquest: "Deliver 1 Large Beast Tear",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "Rhenoplos, Genprey"
   },
   {
      id: 81,
      title: "Sunken Hollow Showdown",
      rank: 4,
      type: "Hunting",
      objective: "Hunt 2 Tetsucabra",
      subquest: "Deliver 1 Large Toad Tear",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "(?)"
   },
   {
      id: 82,
      title: "Pink Stink",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Congalala",
      subquest: "Deliver 1 Territorial Dung+",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Conga, Slagtoth, Deviljho, Gypceros, Savage Deviljho"
   },
   {
      id: 83,
      title: "Distress Signal",
      rank: 4,
      type: "Hunting",
      objective: "Hunt 2 Nerscylla",
      subquest: "Wound a Nerscylla's outer hide",
      location: "Sunken Hollow",
      isKeyQuest: false,
      monsters: "(?)"
   },
   {
      id: 84,
      title: "Material Effect",
      rank: 4,
      type: "Hunting",
      objective: "Hunt a Seltas, a Congalala, and a Gypceros",
      subquest: "Wound the Congalala's comb",
      location: "Primal Forest",
      isKeyQuest: false,
      monsters: "Kelbi, Genprey"
   },
   {
      id: 85,
      title: "Rathian's Wrath",
      rank: 4,
      type: "Urgent",
      objective: "Hunt a Pink Rathian",
      subquest: "Wound the Pink Rathian's wing",
      location: "Sunken Hollow",
      isKeyQuest: true,
      monsters: "Genprey, Aptonoth, Gypceros, Deviljho"
   },
   {
     id: 86,
     title: "Harvest Tour: Frozen Seaway",
     rank: 5,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "N/A",
     location: "Frozen Seaway",
     monsters: "Deviljho, Zamtrios, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 87,
     title: "Harvest Tour: Volcanic Hollow",
     rank: 5,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "N/A",
     location: "Volcanic Hollow",
     monsters: "Deviljho, Iodrome, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 88,
     title: "Harvest Tour: Heaven's Mount",
     rank: 5,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "N/A",
     location: "Heaven's Mount",
     monsters: "Deviljho, Rathalos, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 89,
     title: "Rathian's Wrath",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Pink Rathian",
     subquest: "Wound the Pink Rathian's wing",
     location: "Sunken Hollow",
     monsters: "Genprey, Aptonoth, Purple Gypceros, Deviljho",
     isKeyQuest: false
   },
   {
     id: 90,
     title: "Heat Exhaustion",
     rank: 5,
     type: "Delivery",
     objective: "Deliver 4 Powderstone",
     subquest: "Sever the Rathalos's tail",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Rhenoplos, Rathalos",
     isKeyQuest: false
   },
   {
     id: 91,
     title: "Mistentoe Mission",
     rank: 5,
     type: "Delivery",
     objective: "Deliver 10 Mistentoe",
     subquest: "Sever the Zinogre's tail",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra, Zinogre",
     isKeyQuest: false
   },
   {
     id: 92,
     title: "Zamite Fight",
     rank: 5,
     type: "Hunting",
     objective: "Slay 20 Zamite",
     subquest: "Hunt a Khezu",
     location: "Frozen Seaway",
     monsters: "Zamite, Popo, Khezu",
     isKeyQuest: false
   },
   {
     id: 93,
     title: "Party Pants",
     rank: 5,
     type: "Hunting",
     objective: "Slay 12 Remobra",
     subquest: "Deliver 1 Wyvern Egg",
     location: "Heaven's Mount",
     monsters: "Remobra, Jaggi, Deviljho, Rathalos",
     isKeyQuest: false
   },
   {
     id: 94,
     title: "Poisonous Pair",
     rank: 5,
     type: "Hunting",
     objective: "Hunt 2 Iodrome",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Rhenoplos",
     isKeyQuest: false
   },
   {
     id: 95,
     title: "Lagombi Lair",
     rank: 5,
     type: "Hunting",
     objective: "Hunt 2 Lagombi",
     subquest: "Deliver 1 Large Beast Tear",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 96,
     title: "Fin Finder",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Zamtrios",
     subquest: "Wound the Zamtrios's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite, Lagombi, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 97,
     title: "Cold-blooded Combo",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Zamtrios and a Lagombi",
     subquest: "Wound the Lagombi's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 98,
     title: "Writer's Block",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Najarala and a Rathian",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Primal Forest",
     monsters: "Slagtoth, Genprey",
     isKeyQuest: true
   },
   {
     id: 99,
     title: "The Red Menace",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Red Khezu",
     subquest: "Wound the Red Khezu's head",
     location: "Sunken Hollow",
     monsters: "Konchu, Genprey, Gendrome, Deviljho, Savage Deviljho",
     isKeyQuest: true
   },
   {
     id: 100,
     title: "Trader in Trouble",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Red Khezu and a Pink Rathian",
     subquest: "Sever the Pink Rathian's tail",
     location: "Sunken Hollow",
     monsters: "Konchu, Genprey",
     isKeyQuest: false
   },
   {
     id: 101,
     title: "Electrifying Encounter",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Khezu and a Red Khezu",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 102,
     title: "Royal Rumble",
     rank: 5,
     type: "Capture",
     objective: "Capture a Rathian",
     subquest: "Wound the Rathian's head",
     location: "Primal Forest",
     monsters: "Slagtoth, Genprey, Gravios, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 103,
     title: "Newlywed Game Hunter",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Najarala",
     subquest: "Wound the Najarala's back",
     location: "Primal Forest",
     monsters: "Slagtoth, Ioprey, Gravios, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 104,
     title: "Dread Locked",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Gore Magala",
     subquest: "Wound Gore Magala's wingarm",
     location: "Primal Forest",
     monsters: "Slagtoth, Ioprey",
     isKeyQuest: true
   },
   {
     id: 105,
     title: "Topple the Monarch",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Zinogre",
     subquest: "Wound the Zinogre's head",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra, Seltas, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 106,
     title: "Queen's Academy",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Seltas Queen",
     subquest: "Wound the Seltas Queen's tail",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: false
   },
   {
     id: 107,
     title: "Tigrex by the Tail",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Tigrex",
     subquest: "Wound the Tigrex's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite, Lagombi, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 108,
     title: "Pyres Beware",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Rathian and a Rathalos",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi",
     isKeyQuest: false
   },
   {
     id: 109,
     title: "Temper Tantrum",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Gravios",
     subquest: "Wound the Gravios's chest",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Konchu, Lagombi, Iodrome, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 110,
     title: "Dragons' Tale",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Gravios and a Tigrex",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Primal Forest",
     monsters: "Slagtoth, Konchu",
     isKeyQuest: false
   },
   {
     id: 111,
     title: "Gathering of Dragons",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Rathian, a Rathalos, and a Tigrex",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi",
     isKeyQuest: false
   },
   {
     id: 112,
     title: "Primal Forest M.I.A.",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Najarala, a Gravios, and a Gore Magala",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Primal Forest",
     monsters: "Slagtoth, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 113,
     title: "Advanced: Frenzied Foe",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Frenzied Tigrex",
     subquest: "Break the Tigrex's claw",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi, Seltas, Deviljho, Savage Deviljho",
     isKeyQuest: true
   },
   {
     id: 114,
     title: "Advanced: Approaching Storm",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Frenzied Zinogre",
     subquest: "Wound the Zinogre's head",
     location: "Heaven's Mount",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 115,
     title: "Advanced: Eerie Aerie",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Frenzied Rathalos",
     subquest: "Wound the Rathalos's head",
     location: "Heaven's Mount",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 116,
     title: "Advanced: Bug Bite",
     rank: 5,
     type: "Hunting",
     objective: "Hunt a Frenzied Seltas Queen",
     subquest: "Hunt a Seltas",
     location: "Heaven's Mount",
     monsters: "Seltas",
     isKeyQuest: false
   },
   {
     id: 117,
     title: "Ore D'oeuvre",
     rank: 5,
     type: "Urgent",
     objective: "Hunt a Black Gravios",
     subquest: "Wound Black Gravios's back",
     location: "Primal Forest",
     monsters: "Slagtoth, Konchu",
     isKeyQuest: true
   },
   {
     id: 118,
     title: "Ore D'oeuvre",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Black Gravios",
     subquest: "Wound Black Gravios's back",
     location: "Primal Forest",
     monsters: "Slagtoth, Konchu, Iodrome, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 119,
     title: "Bring Down the Sky King",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Azure Rathalos",
     subquest: "Wound the Azure Rathalos's wing",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra, Seltas, Deviljho, Savage Deviljho",
     isKeyQuest: true
   },
   {
     id: 120,
     title: "Infernal Overlord",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Stygian Zinogre",
     subquest: "Wound Stygian Zinogre's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite, Lagombi, Deviljho, Savage Deviljho",
     isKeyQuest: true
   },
   {
     id: 121,
     title: "Ear Ache",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Brute Tigrex",
     subquest: "Wound the Brute Tigrex's head",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Rhenoplos, Iodrome, Deviljho, Savage Deviljho",
     isKeyQuest: true
   },
   {
     id: 122,
     title: "Brimstone and Brachydios",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Brachydios",
     subquest: "Wound the Brachydios's head",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Rhenoplos, Iodrome, Deviljho, Savage Deviljho",
     isKeyQuest: true
   },
   {
     id: 123,
     title: "Advanced: Dance with Dragons",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Black Gravios, a Brute Tigrex, and a Brachydios",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Rhenoplos",
     isKeyQuest: false
   },
   {
     id: 124,
     title: "Advanced: Mega Hunt-a-thon",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Stygian Zinogre, a Azure Rathalos, a Seltas Queen, and a Seltas",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: false
   },
   {
     id: 125,
     title: "Advanced: Dragon Attack",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Brute Tigrex and a Stygian Zinogre",
     subquest: "Sever the Brute Tigrex's tail",
     location: "Arena",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 126,
     title: "Advanced: Heaven and Earth",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Azure Rathalos and a Pink Rathian",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Heaven's Mount",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 127,
     title: "Advanced: Forest Gone Wild",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Frenzied Tigrex and a Frenzied Brute Tigrex",
     subquest: "Sever the Tigrex's tail",
     location: "Primal Forest",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 128,
     title: "Advanced: Armor Amore",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Frenzied Gravios and a Frenzied Black Gravios",
     subquest: "Sever the Black Gravios's tail",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 129,
     title: "Advanced: Arena Emergency",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Frenzied Zinogre and a Frenzied Stygian Zinogre",
     subquest: "Sever the Stygian Zinogre's tail",
     location: "Arena",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 130,
     title: "Advanced: Pair of Kings",
     rank: 6,
     type: "Hunting",
     objective: "Hunt a Frenzied Rathalos and a Frenzied Azure Rathalos",
     subquest: "Sever the Azure Rathalos' tail",
     location: "Volcanic Hollow",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 131,
     title: "Advanced: Wake-up Call",
     rank: 6,
     type: "Capture",
     objective: "Capture a Frenzied Brute Tigrex",
     subquest: "Break the Brute Tigrex's claw",
     location: "Primal Forest",
     monsters: "Gendrome, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 132,
     title: "Advanced: Gravios Fortunes",
     rank: 6,
     type: "Capture",
     objective: "Capture a Frenzied Black Gravios",
     subquest: "Wound the Black Gravios's head",
     location: "Primal Forest",
     monsters: "Slagtoth, Bnahabra, Gendrome, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 133,
     title: "Advanced: Insecticide",
     rank: 6,
     type: "Capture",
     objective: "Capture a Frenzied Stygian Zinogre",
     subquest: "Wound the monster's front leg",
     location: "Volcanic Hollow",
     monsters: "Iodrome, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 134,
     title: "Advanced: Azure Alert",
     rank: 6,
     type: "Capture",
     objective: "Capture a Frenzied Azure Rathalos",
     subquest: "Wound the Azure Rathalos's wing",
     location: "Volcanic Hollow",
     monsters: "Iodrome, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 135,
     title: "Advanced: Bag a Brachydios",
     rank: 6,
     type: "Capture",
     objective: "Capture a Frenzied Brachydios",
     subquest: "Wound the Brachydios's front leg",
     location: "Volcanic Hollow",
     monsters: "Iodrome, Deviljho, Savage Deviljho",
     isKeyQuest: false
   },
   {
     id: 136,
     title: "Advanced: Stop the Wheel",
     rank: 6,
     type: "Hunting",
     objective: "Slay a Shagaru Magala",
     subquest: "Break Shagaru Magala's horns",
     location: "Sanctuary",
     monsters: "N/A",
     isKeyQuest: true
   },
   {
     id: 137,
     title: "Devil of a Problem",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Deviljho",
     subquest: "Wound the Deviljho's Head",
     location: "Frozen Seaway",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 138,
     title: "Ring of the Silver Sol",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Silver Rathalos",
     subquest: "Wound the Silver Rathalos' Head",
     location: "Tower Summit",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 139,
     title: "Ring of the Golden Lune",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Gold Rathian",
     subquest: "Wound the Gold Rathian's Head",
     location: "Tower Summit",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 140,
     title: "Sinister Astronomy",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Silver Rathalos & 1 Gold Rathian",
     subquest: "Wound the Gold Rathian's Back",
     location: "Tower Summit",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 141,
     title: "Busted Hell Hunters",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Molten Tigrex",
     subquest: "Wound the Molten Tigrex's Head",
     location: "Tower Summit",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 142,
     title: "Advanced: Stop the Wheel",
     rank: 7,
     type: "Hunting",
     objective: "Slay 1 Shagaru Magala",
     subquest: "Break the Shagaru Magala's horns",
     location: "Sanctuary",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 143,
     title: "Advanced: Grim Tidings",
     rank: 7,
     type: "Hunting",
     objective: "Slay 1 Akantor",
     subquest: "Wound the Akantor's head",
     location: "Ingle Isle",
     monsters: "N/A",
     isKeyQuest: true
   },
   {
     id: 144,
     title: "Advanced: Teostra Tangle",
     rank: 7,
     type: "Hunting",
     objective: "Slay or Repel 1 Teostra",
     subquest: "Wound the Teostra's head",
     location: "Volcanic Hollow",
     monsters: "(?)",
     isKeyQuest: true
   },
   {
     id: 145,
     title: "Advanced: Storm Front",
     rank: 7,
     type: "Hunting",
     objective: "Slay or Repel 1 Kushala Daora",
     subquest: "Wound the Kushala Daora's head",
     location: "Frozen Seaway",
     monsters: "(?)",
     isKeyQuest: true
   },
   {
     id: 146,
     title: "Advanced: The Raging Rajang",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Rajang",
     subquest: "Wound the Rajang's Tail",
     location: "Primal Forest",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 147,
     title: "Advanced: Fleet Action",
     rank: 7,
     type: "Hunting",
     objective: "Slay or Repel 1 Dah'ren Mohran",
     subquest: "Break Dah'ren Mohran's Horn",
     location: "Great Desert",
     monsters: "Delex",
     isKeyQuest: true
   },
   {
     id: 148,
     title: "Advanced: Bet Your Life",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Deviljho & 1 Rajang",
     subquest: "Sever the Deviljho's Tail",
     location: "Ancestral Steppe",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 149,
     title: "Advanced: Speartip Menace",
     rank: 7,
     type: "Urgent",
     objective: "Slay 1 Dalamadur",
     subquest: "Wound the Dalamadur's Head",
     location: "Speartip Crag",
     monsters: "N/A",
     isKeyQuest: true
   },
   {
     id: 150,
     title: "Advanced: Stormy Knight",
     rank: 7,
     type: "Hunting",
     objective: "Slay or Repel 1 Kushala Daora",
     subquest: "None",
     location: "Frozen Seaway",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 151,
     title: "Advanced: Seek the Hide",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Furious Rajang",
     subquest: "Break the Rajang's Horns",
     location: "Ancestral Steppe",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 152,
     title: "Advanced: More Mohran",
     rank: 7,
     type: "Hunting",
     objective: "Hunt or Repel 1 Dah'ren Mohran",
     subquest: "None",
     location: "Great Desert",
     monsters: "Delex",
     isKeyQuest: false
   },
   {
     id: 153,
     title: "Advanced: Akantor Coup",
     rank: 7,
     type: "Hunting",
     objective: "Slay 1 Akantor",
     subquest: "None",
     location: "Ingle Isle",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 154,
     title: "Advanced: Fade to Black",
     rank: 7,
     type: "Hunting",
     objective: "Slay or Repel 1 Fatalis",
     subquest: "None",
     location: "Castle Schrade",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 155,
     title: "Advanced: Queen Slayer",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Rathian, 1 Pink Rathian, and 1 Gold Rathian",
     subquest: "None",
     location: "Tower Summit",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 156,
     title: "Advanced: King Slayer",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 1 Rathalos, 1 Azure Rathalos, and 1 Silver Rathalos",
     subquest: "None",
     location: "Tower Summit",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 157,
     title: "Advanced: Enraged Rajang",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 2 Furious Rajang",
     subquest: "None",
     location: "Primal Forest",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 158,
     title: "Advanced: Naked and Afraid",
     rank: 7,
     type: "Hunting",
     objective: "Hunt 2 Deviljho",
     subquest: "None",
     location: "Arena",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 159,
     title: "Advanced: Here to Eternity",
     rank: 7,
     type: "Hunting",
     objective: "Slay 1 Dalamadur",
     subquest: "None",
     location: "Speartip Crag",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 160,
     title: "Advanced: Glacial Grinder",
     rank: 7,
     type: "Hunting",
     objective: "Slay 1 Ukanlos",
     subquest: "Topple monster while mounted",
     location: "Polar Field",
     monsters: "N/A",
     isKeyQuest: true
   },
   {
     id: 161,
     title: "Harvest Tour: Anc. Steppe",
     rank: 8,
     type: "Gathering",
     objective: "Deliver 1 Paw Pass Ticket",
     subquest: "Hunt a Seltas",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi, Seltas",
     isKeyQuest: false
   },
   {
     id: 162,
     title: "Harvest Tour: Sunken Hollow",
     rank: 8,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "Hunt a Gypceros",
     location: "Sunken Hollow",
     monsters: "Aptonoth, Genprey, Gypceros",
     isKeyQuest: false
   },
   {
     id: 163,
     title: "Harvest Tour: Primal Forest",
     rank: 8,
     type: "Gathering",
     objective: "Deliver 1 Paw Pass Ticket",
     subquest: "Hunt an Iodrome",
     location: "Primal Forest",
     monsters: "Conga, Genprey, Iodrome",
     isKeyQuest: false
   },
   {
     id: 164,
     title: "Harvest Tour: Frozen Seaway",
     rank: 8,
     type: "Gathering",
     objective: "Deliver 1 Paw Pass Ticket",
     subquest: "Hunt a Khezu",
     location: "Frozen Seaway",
     monsters: "Khezu",
     isKeyQuest: false
   },
   {
     id: 165,
     title: "Harvest Tour: Dunes (Day)",
     rank: 8,
     type: "Gathering",
     objective: "Deliver 1 Paw Pass Ticket",
     subquest: "Hunt a Cephadrome",
     location: "Dunes",
     monsters: "Hermitaur, Bnahabra, Cephadrome",
     isKeyQuest: false
   },
   {
     id: 166,
     title: "Birthday Berries",
     rank: 8,
     type: "Hunting",
     objective: "Deliver 8 Tropical Berries",
     subquest: "N/A",
     location: "Dunes",
     monsters: "Hermitaur, Apceros",
     isKeyQuest: false
   },
   {
     id: 167,
     title: "Netting Neopterons",
     rank: 8,
     type: "Hunting",
     objective: "Slay 30 Bnahabra",
     subquest: "Slay 8 Konchu",
     location: "Dunes",
     monsters: "Bnahabra, Konchu",
     isKeyQuest: false
   },
   {
     id: 168,
     title: "All-You-Can-Hunt Zamite",
     rank: 8,
     type: "Hunting",
     objective: "Slay 25 Zamite",
     subquest: "Hunt a Zamtrios",
     location: "Frozen Seaway",
     monsters: "Zamite, Melynx, Zamtrios",
     isKeyQuest: false
   },
   {
     id: 169,
     title: "Sculptural Seltas",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Desert Seltas",
     subquest: "N/A",
     location: "Ancestral Steppe",
     monsters: "Jaggi, Aptonoth, Rajang",
     isKeyQuest: true
   },
   {
     id: 170,
     title: "Lumber Support",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Kecha Wacha",
     subquest: "Slay 7 Genprey",
     location: "Primal Forest",
     monsters: "Altaroth, Bnahabra, Genprey, Iodrome, Rajang, Apex Rajang",
     isKeyQuest: false
   },
   {
     id: 171,
     title: "Seeing Spots",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Ash Kecha Wacha",
     subquest: "Wound Ash Kecha Wacha's ears",
     location: "Ancestral Steppe",
     monsters: "Jaggi, Aptonoth",
     isKeyQuest: true
   },
   {
     id: 172,
     title: "Chasing Tail",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Tetsucabra",
     subquest: "Deliver 1 Large Toad Tear",
     location: "Sunken Hollow",
     monsters: "Jaggi, Rhenoplos",
     isKeyQuest: false
   },
   {
     id: 173,
     title: "Berserker Rage",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Berserk Tetsucabra",
     subquest: "Wound the Berserk Tetsucabra's jaw",
     location: "Sunken Hollow",
     monsters: "Jaggi, Rhenoplos, Rajang, Tetsucabra",
     isKeyQuest: true
   },
   {
     id: 174,
     title: "Purple Pros",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Purple Gypceros",
     subquest: "Slay 8 Altaroth",
     location: "Sunken Hollow",
     monsters: "Rhenoplos, Genprey",
     isKeyQuest: false
   },
   {
     id: 175,
     title: "Line in the Sand",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Cephadrome",
     subquest: "Wound the Cephadrome's tail",
     location: "Dunes",
     monsters: "Cephalos, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 176,
     title: "Hunger Games",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Congalala",
     subquest: "Deliver 1 Territorial Dung+",
     location: "Primal Forest",
     monsters: "Bnahabra, Genprey",
     isKeyQuest: false
   },
   {
     id: 177,
     title: "Primate Plunder",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Emerald Congalala",
     subquest: "Break Emerald Congalala's claw",
     location: "Ancestral Steppe",
     monsters: "Jaggi, Aptonoth",
     isKeyQuest: false
   },
   {
     id: 178,
     title: "Fashion Victim",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Daimyo Hermitaur",
     subquest: "Break Daimyo Hermitaur's shell",
     location: "Primal Forest",
     monsters: "Bnahabra, Genprey",
     isKeyQuest: true
   },
   {
     id: 179,
     title: "Hit List: Plum Daimyo Hermitaur",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Plum Daimyo Hermitaur",
     subquest: "Break both of Plum Daimyo Hermitaur's claws",
     location: "Dunes",
     monsters: "Hermitaur, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 180,
     title: "Lagombi Lair",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Lagombi",
     subquest: "Deliver 1 Large Beast Tear",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 181,
     title: "Death and Taxidermy",
     rank: 8,
     type: "Hunting",
     objective: "Capture a Nerscylla",
     subquest: "Slay 5 Slagtoth",
     location: "Primal Forest",
     monsters: "Bnahabra, Genprey",
     isKeyQuest: false
   },
   {
     id: 182,
     title: "Grand Finals Confrontation",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Tigerstripe Zamtrios",
     subquest: "Wound Tigerstripe Zamtrios's fin",
     location: "Dunes",
     monsters: "Bnahabra, Hermitaur",
     isKeyQuest: true
   },
   {
     id: 183,
     title: "Serpentine Samba",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Najarala",
     subquest: "Wound the Najarala's head",
     location: "Primal Forest",
     monsters: "Bnahabra, Genprey",
     isKeyQuest: false
   },
   {
     id: 184,
     title: "Serpent Serenade",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 1 Tidal Najarala",
     subquest: "Break Tidal Najarala's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: true
   },
   {
     id: 185,
     title: "Hunter In Green and Red",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Rathian and a Red Khezu",
     subquest: "Deliver 1 Lrg Wyvern Tear",
     location: "Sunken Hollow",
     monsters: "Konchu, Genprey",
     isKeyQuest: true
   },
   {
     id: 186,
     title: "Royal Assassination",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Rathian",
     subquest: "Wound the Rathian's back",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi",
     isKeyQuest: false
   },
   {
     id: 187,
     title: "Pink Problems",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Pink Rathian",
     subquest: "Slay 4 Apceros",
     location: "Dunes",
     monsters: "Bnahabra, Hermitaur, Apceros",
     isKeyQuest: false
   },
   {
     id: 188,
     title: "La Vie en Rose",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Red Khezu",
     subquest: "Wound the Red Khezu's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 189,
     title: "Hunt-a-thon: Khezu",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Khezu before time expires or deliver a Paw Pass Ticket",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Sunken Hollow",
     monsters: "Konchu, Genprey",
     isKeyQuest: false
   },
   {
     id: 190,
     title: "Advanced: Bug-Be-Gone",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Seltas and a Desert Seltas",
     subquest: "Deliver 1 Queen Substance",
     location: "Ancestral Steppe",
     monsters: "Jaggi, Aptonoth",
     isKeyQuest: false
   },
   {
     id: 191,
     title: "Advanced: Terrible Twins",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Kecha Wacha and an Ash Kecha Wacha",
     subquest: "Deliver 1 Large Beast Tear",
     location: "Primal Forest",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 192,
     title: "Advanced: Claw Clash",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Daimyo Hermitaur and a Plum Daimyo Hermitaur",
     subquest: "Deliver 1 Crab Pearl+",
     location: "Dunes",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 193,
     title: "Advanced: Hollow Hysterics",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Nerscylla and a Tetsucabra",
     subquest: "Wound the Tetsucabra's back",
     location: "Dunes",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 194,
     title: "Advanced: Chumming the Waters",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Frenzied Zamtrios",
     subquest: "Wound the Zamtrios's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 195,
     title: "Advanced: Chumming the Waters",
     rank: 8,
     type: "Hunting",
     objective: "Hunt 2 Frenzied Zamtrios",
     subquest: "Wound the Zamtrios's head",
     location: "Frozen Seaway",
     monsters: "Popo, Zamite",
     isKeyQuest: false
   },
   {
     id: 196,
     title: "Advanced: Tiger-sharq",
     rank: 8,
     type: "Hunting",
     objective: "Hunt a Tigerstripe Zamtrios",
     subquest: "Suppress its Frenzy (2x)",
     location: "Dunes",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 197,
     title: "Advanced: Frenzied Trading",
     rank: 8,
     type: "Hunting",
     objective: "",
     subquest: "Capture an Iodrome",
     location: "Primal Forest",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 198,
     title: "Seer of Swords",
     rank: 8,
     type: "Urgent",
     objective: "Hunt 1 Seregios",
     subquest: "Cut Seregios's tail",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi",
     isKeyQuest: true
   },
   {
     id: 199,
     title: "Harvest Tour: Volcanic Hollow",
     rank: 9,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "Hunt a Tetsucabra",
     location: "Volcanic Hollow",
     monsters: "Slagtoth, Ioprey, Tetsucabra",
     isKeyQuest: false
   },
   {
     id: 200,
     title: "Harvest Tour: Heaven's Mount",
     rank: 9,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "Hunt a Congalala",
     location: "Heaven's Mount",
     monsters: "Remobra, Conga, Congalala",
     isKeyQuest: false
   },
   {
     id: 201,
     title: "Harvest Tour: Dunes (Night)",
     rank: 9,
     type: "Gathering",
     objective: "Survive until time expires or deliver a Paw Pass Ticket",
     subquest: "Hunt a Pink Rathian",
     location: "Dunes",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 202,
     title: "Seer of Swords",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Seregios",
     subquest: "Sever the Seregios's tail",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Jaggi",
     isKeyQuest: false
   },
   {
     id: 203,
     title: "Out for the Count",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 2 Seregios",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Dunes",
     monsters: "Remobra, Delex",
     isKeyQuest: false
   },
   {
     id: 204,
     title: "All-You-Can-Hunt Remobra",
     rank: 9,
     type: "Hunting",
     objective: "Slay 15 Remobra",
     subquest: "Deliver 1 Meteor Chunk",
     location: "Dunes",
     monsters: "Remobra, Apceros, Plum Daimyo Hermitaur",
     isKeyQuest: false
   },
   {
     id: 205,
     title: "Course Correction",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Shrouded Nerscylla",
     subquest: "Wound S.Nerscylla's outer hide",
     location: "Dunes",
     monsters: "Bnahabra, Apceros",
     isKeyQuest: true
   },
   {
     id: 206,
     title: "Sovereign of the Sky",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Rathalos",
     subquest: "Wound the Rathalos's back",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: false
   },
   {
     id: 207,
     title: "Rival Clash",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Seregios and a Rathalos",
     subquest: "Break the Seregios's horn",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: false
   },
   {
     id: 208,
     title: "The Azure King and the Tyrant",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Azure Rathalos and 1 Tigrex",
     subquest: "Deliver 1 Lrg Wyvern Tear",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: true
   },
   {
     id: 209,
     title: "Azure Arrival",
     rank: 9,
     type: "Hunting",
     objective: "Hunt an Azure Rathalos",
     subquest: "Wound Azure Rathalos's head",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Konchu",
     isKeyQuest: false
   },
   {
     id: 210,
     title: "Beast Not Quite Busted",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Tigrex",
     subquest: "Slay 10 Bnahabra",
     location: "Sunken Hollow",
     monsters: "Genprey, Aptonoth",
     isKeyQuest: false
   },
   {
     id: 211,
     title: "Brute Force",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Brute Tigrex",
     subquest: "Wound the Brute Tigrex's head",
     location: "Dunes",
     monsters: "Hermitaur, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 212,
     title: "Strutting the Royal Runway",
     rank: 9,
     type: "Hunting",
     objective: "Capture a Seltas Queen",
     subquest: "Capture a Seltas",
     location: "Heaven's Mount",
     monsters: "Ioprey, Kelbi, Seltas",
     isKeyQuest: false
   },
   {
     id: 213,
     title: "Pestering Pest",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Desert Seltas Queen",
     subquest: "Wound D.Seltas Queen's tail",
     location: "Dunes",
     monsters: "Apceros, Bnahabra, Desert Seltas",
     isKeyQuest: true
   },
   {
     id: 214,
     title: "Temper Tantrum",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Gravios",
     subquest: "Wound the Gravios's head",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 215,
     title: "Hollow Promise",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Black Gravios",
     subquest: "Wound the Black Gravios's chest",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 216,
     title: "How to Zap Your Zinogre",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Zinogre",
     subquest: "Slay 5 Slagtoth",
     location: "Primal Forest",
     monsters: "Bnahabra, Genprey, Slagtoth",
     isKeyQuest: true
   },
   {
     id: 217,
     title: "Mountain Rescue",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Stygian Zinogre",
     subquest: "Slay 8 Ioprey",
     location: "Heaven's Mount",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 218,
     title: "Fire Drill",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Brachydios and 1 Stygian Zinogre",
     subquest: "Sever the Stygian Zinogre's tail",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 219,
     title: "Fire and Ice",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Brachydios",
     subquest: "Sever the Brachydios's tail",
     location: "Frozen Seaway",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 220,
     title: "Showdown at High Noon",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Diablos",
     subquest: "Sever the Diablos's tail",
     location: "Dunes",
     monsters: "Hermitaur, Bnahabra",
     isKeyQuest: true
   },
   {
     id: 221,
     title: "Showdown at Midnight",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Black Diablos",
     subquest: "Break both of Black Diablos's horns",
     location: "Dunes",
     monsters: "Konchu, Rhenoplos",
     isKeyQuest: true
   },
   {
     id: 222,
     title: "Locked Horns",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Diablos and Black Diablos",
     subquest: "Break the Diablos's horns",
     location: "Dunes",
     monsters: "Hermitaur, Apceros",
     isKeyQuest: false
   },
   {
     id: 223,
     title: "Ring Hollow",
     rank: 9,
     type: "Hunting",
     objective: "Hunt all large monsters",
     subquest: "Deliver 1 Large Wyvern Tear",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Rhenoplos",
     isKeyQuest: false
   },
   {
     id: 224,
     title: "Advanced: Mean and Green",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Emerald Congalala and 1 Seltas Queen",
     subquest: "Hunt a Seltas",
     location: "Ancestral Steppe",
     monsters: "(?)",
     isKeyQuest: false
   },
   {
     id: 225,
     title: "Advanced: Bolt of Pink",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 1 Zinogre and 1 Pink Rathian",
     subquest: "Sever the Zinogre's tail",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: false
   },
   {
     id: 226,
     title: "Advanced: Spider Study",
     rank: 9,
     type: "Hunting",
     objective: "Hunt 2 Shrouded Nerscylla",
     subquest: "Suppress its Frenzy (2x)",
     location: "Dunes",
     monsters: "Bnahabra, Apceros",
     isKeyQuest: false
   },
   {
     id: 227,
     title: "Advanced: Escaped Convicts",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Cephadrome and a Desert Seltas Queen",
     subquest: "Suppress S.Queen's Frenzy",
     location: "Dunes",
     monsters: "Cephalos, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 228,
     title: "Advanced: A Black Day",
     rank: 9,
     type: "Hunting",
     objective: "Hunt a Black Gravios and a Brute Tigrex",
     subquest: "Break the Brute Tigrex's claw",
     location: "Primal Forest",
     monsters: "Brute Tigrex",
     isKeyQuest: false
   },
   {
     id: 229,
     title: "Advanced: A Plague Awoken",
     rank: 9,
     type: "Urgent",
     objective: "Hunt 1 Chaotic Gore Magala",
     subquest: "Break Chaotic Gore Magala's left wing",
     location: "Heaven's Mount",
     monsters: "Chaotic Gore Magala",
     isKeyQuest: true
   },
   {
     id: 230,
     title: "Into the Heavens",
     rank: 10,
     type: "Hunting",
     objective: "Hunt 1 Stygian Zinogre and 1 Chaotic Gore Magala",
     subquest: "Wound Gore Magala's head",
     location: "Heaven's Mount",
     monsters: "Ioprey, Remobra",
     isKeyQuest: false
   },
   {
     id: 231,
     title: "Grim Quartet",
     rank: 10,
     type: "Hunting",
     objective: "Hunt 1 Zinogre, 1 Tidal Najarala, 1 Tigrex, and 1 Gravios",
     subquest: "N/A",
     location: "Arena",
     monsters: "Zingore, Tidal Najarala, Tigrex, Gravios",
     isKeyQuest: false
   },
   {
     id: 232,
     title: "The Sky Is Falling",
     rank: 10,
     type: "Hunting",
     objective: "Hunt 1 Molten Tigrex",
     subquest: "Wound the Molten Tigrex's head",
     location: "Tower Summit",
     monsters: "Molten Tigrex",
     isKeyQuest: false
   },
   {
     id: 233,
     title: "Advanced: A Plague Awoken",
     rank: 10,
     type: "Hunting",
     objective: "Hunt a Chaotic Gore Magala",
     subquest: "Break Gore Magala's left wing",
     location: "Heaven's Mount",
     monsters: "Chaotic Gore Magala",
     isKeyQuest: false
   },
   {
     id: 234,
     title: "Advanced: A Formless Fiend",
     rank: 10,
     type: "Hunting",
     objective: "Slay or Repel a Chameleos",
     subquest: "Break Chameleos's horn",
     location: "Primal Forest",
     monsters: "Bnahabra",
     isKeyQuest: true
   },
   {
     id: 235,
     title: "Advanced: Misty Challenge",
     rank: 10,
     type: "Hunting",
     objective: "Slay 1 Chameleos or repel it",
     subquest: "Topple monster while mounted",
     location: "Ancestral Steppe",
     monsters: "Chameleos",
     isKeyQuest: false
   },
   {
     id: 236,
     title: "Advanced: A Storm of Steel",
     rank: 10,
     type: "Hunting",
     objective: "Slay or Repel 1 Kushala Daora",
     subquest: "Sever the Kushala Daora's tail",
     location: "Dunes",
     monsters: "Bnahabra",
     isKeyQuest: true
   },
   {
     id: 237,
     title: "Advanced: Emperor of Embers",
     rank: 10,
     type: "Hunting",
     objective: "Slay or Repel 1 Teostra",
     subquest: "Break Teostra's wings",
     location: "Dunes",
     monsters: "Bnahabra",
     isKeyQuest: true
   },
   {
     id: 238,
     title: "Advanced: Icy Investigation",
     rank: 10,
     type: "Hunting",
     objective: "Slay 1 Ukanlos",
     subquest: "Wound the Ukanlos's front leg",
     location: "Polar Field",
     monsters: "N/A",
     isKeyQuest: true
   },
   {
     id: 239,
     title: "Advanced: Fur Fixation",
     rank: 10,
     type: "Hunting",
     objective: "Hunt a Furious Rajang",
     subquest: "Break the Rajang's horns",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 240,
     title: "Advanced: Lab Partners",
     rank: 10,
     type: "Hunting",
     objective: "Hunt 1 Frenzied Brachydios and 1 Frenzied Azure Rathalos",
     subquest: "Suppress Brachydios's Frenzy",
     location: "Volcanic Hollow",
     monsters: "Ioprey, Konchu",
     isKeyQuest: false
   },
   {
     id: 241,
     title: "Advanced: The Scathing Shore",
     rank: 10,
     type: "Hunting",
     objective: "Hunt 1 Frenzied Seregios, 1 Frenzied Black Diablos, and 1 Frenzied Rajang",
     subquest: "Break the Black Diablos's back",
     location: "Dunes",
     monsters: "Apceros, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 242,
     title: "Advanced: Wheel of Time",
     rank: 10,
     type: "Hunting",
     objective: "Slay 1 Shagaru Magala",
     subquest: "Break Shagaru Magala's horns",
     location: "Sanctuary",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 243,
     title: "Advanced: Winds of Discord",
     rank: 10,
     type: "Hunting",
     objective: "Slay 1 Rusted Kushala Daora",
     subquest: "N/A",
     location: "Polar Field",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 244,
     title: "Advanced: Rhapsody in Rime",
     rank: 10,
     type: "Hunting",
     objective: "",
     subquest: "",
     location: "",
     monsters: "'",
     isKeyQuest: false
   },
   {
     id: 245,
     title: "Advanced: Tigrex In Effect",
     rank: 10,
     type: "Hunting",
     objective: "Hunt 1 Tigrex",
     subquest: "Wound the Tigrex's head.",
     location: "Sunken Hollow",
     monsters: "Jaggi, Jaggia",
     isKeyQuest: false
   },
   {
     id: 246,
     title: "Advanced: Fury on the Mount",
     rank: 10,
     type: "Hunting",
     objective: "",
     subquest: "",
     location: "",
     monsters: "'",
     isKeyQuest: false
   },
   {
     id: 247,
     title: "Advanced: Gravios Situation",
     rank: 10,
     type: "Hunting",
     objective: "",
     subquest: "",
     location: "",
     monsters: "'",
     isKeyQuest: false
   },
   {
     id: 248,
     title: "Advanced: The Wailing Devil",
     rank: 10,
     type: "Hunting",
     objective: "",
     subquest: "",
     location: "",
     monsters: "'",
     isKeyQuest: false
   },
   {
     id: 249,
     title: "Advanced: Dark Domination",
     rank: 10,
     type: "Hunting",
     objective: "Slay an Akantor",
     subquest: "Wound the Akantor's back",
     location: "Ingle Isle",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 250,
     title: "Advanced: 1,001 Shards",
     rank: 10,
     type: "Hunting",
     objective: "Hunt an Apex Seregios",
     subquest: "Break the Seregios's leg claw",
     location: "Dunes",
     monsters: "Hermitaur, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 251,
     title: "Advanced: Wings of Woe",
     rank: 10,
     type: "Hunting",
     objective: "Hunt a Chaotic Gore Magala",
     subquest: "Wound Gore Magala's right wingarm",
     location: "Heaven's Mount",
     monsters: "Ioprey, Aptonoth",
     isKeyQuest: false
   },
   {
     id: 252,
     title: "Advanced: Eternal Emperor",
     rank: 10,
     type: "Hunting",
     objective: "Slay a Shah Dalamadur",
     subquest: "Wound Shah Dalamadur's back",
     location: "Speartip Crag",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 253,
     title: "Advanced: Beyond Brawn",
     rank: 10,
     type: "Hunting",
     objective: "Hunt an Apex Rajang",
     subquest: "Break the Rajang's horns",
     location: "Ancestral Steppe",
     monsters: "Aptonoth, Bnahabra",
     isKeyQuest: false
   },
   {
     id: 254,
     title: "Advanced: Achy Brachy Heart",
     rank: 10,
     type: "Hunting",
     objective: "Slay a Raging Brachydios",
     subquest: "Wound the Brachydios's head",
     location: "Ingle Isle",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 255,
     title: "Advanced: Silver Cataclysm",
     rank: 10,
     type: "Hunting",
     objective: "Slay an Ukanlos",
     subquest: "Wound the Ukanlos's chin",
     location: "Polar Field",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 256,
     title: "Advanced: Act of Gog",
     rank: 10,
     type: "Hunting",
     objective: "",
     subquest: "",
     location: "",
     monsters: "'",
     isKeyQuest: false
   },
   {
     id: 257,
     title: "Advanced: A Final Battle Cry",
     rank: 10,
     type: "Hunting",
     objective: "Slay a Crimson Fatalis or repel it.",
     subquest: "N/A",
     location: "Ingle Isle",
     monsters: "N/A",
     isKeyQuest: false
   },
   {
     id: 258,
     title: "Advanced: Monster Hunter!",
     rank: 10,
     type: "Hunting",
     objective: "",
     subquest: "",
     location: "",
     monsters: "'",
     isKeyQuest: false
   },
   {
     id: 259,
     title: "Advanced: Quagmire Quarrel",
     rank: 10,
     type: "Urgent",
     objective: "Slay 1 Gogmazios",
     subquest: "Break Gogmazios's back",
     location: "Battlequarters",
     monsters: "Gogmazios",
     isKeyQuest: true
   }
]
